apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    steps:
      - name: Deploy TestApp-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].digest }}
          target-environment: pre-prod
          name: TestApp-Frontend

      - name: Deploy TestApp-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].digest }}
          target-environment: pre-prod
          name: TestApp-Backend

      - name: Deploy TestApp-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].digest }}
          target-environment: pre-prod
          name: TestApp-APIs
  prod:
    needs: pre-prod
    steps:
      - name: Deploy TestApp-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-Frontend']['TestApp-Frontend'].digest }}
          target-environment: prod
          name: TestApp-Frontend

      - name: Deploy TestApp-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-Backend']['TestApp-Backend'].digest }}
          target-environment: prod
          name: TestApp-Backend

      - name: Deploy TestApp-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['TestApp-APIs']['TestApp-APIs'].digest }}
          target-environment: prod
          name: TestApp-APIs
